# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1InVS-JODu8oWw4gAekqcmlh_6tyTsTKx
"""

!pip install ultralytics opencv-python

import cv2
from ultralytics import YOLO

def load_model():
    model = YOLO('yolov8n.pt')  # Используем модель с наименьшими весами для скорости
    return model

def process_video(input_file, output_file):
    model = load_model()
    cap = cv2.VideoCapture(input_file)
    if not cap.isOpened():
        print(f"Ошибка: не удалось открыть файл {input_file}")
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = int(cap.get(cv2.CAP_PROP_FPS))

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_file, fourcc, fps, (width, height))
    if not out.isOpened():
        print("Ошибка: не удалось открыть файл для записи.")


    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        results = model(frame)

        for result in results:
            boxes = result.boxes
            for box in boxes:
                if box.cls == 0:
                    x1, y1, x2, y2 = map(int, box.xyxy[0])
                    confidence = box.conf[0]
                    label = f"Person {confidence:.2f}"

                    cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
                    cv2.putText(frame, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

        out.write(frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    out.release()
    cv2.destroyAllWindows()

#from google.colab import files
#uploaded = files.upload()

input_file = 'crowd.mp4'
output_file = "output_crowd_yolov8.mp4"
x = process_video(input_file, output_file)